Update base homepage
shepkeira/LIMS pull request #282
Opened 2022-03-11 18:38 UTC by sayo96825

base page with link states and updated main home page

2022-03-11 19:54 UTC, shepkeira requested changes

2022-03-11 19:54 UTC, shepkeira commented on LIMS_IMAGE/web/templates/home.html
> +<link rel="stylesheet" href="{% static 'css/home.css' %}"/>
This should be inside a head tag, as below
```
<head>
  <link rel="stylesheet" href="{% static 'css/home.css' %}"/>
</head>
```

2022-03-11 19:54 UTC, shepkeira commented on LIMS_IMAGE/web/templates/home.html
> +        <h2>Welcome to the LIMS home page</h2>
we can remove this line

2022-03-11 19:54 UTC, shepkeira commented on LIMS_IMAGE/web/templates/home.html
> +            <img src ="{% static 'image/images2.jpg' %}" alt ="Background image with Laboraroty theme" height = 500px width = 800px>
this image should have a meaningful name like "homepage_image.jpg"

2022-03-11 19:54 UTC, shepkeira commented on LIMS_IMAGE/web/templates/home.html
> +            <img src ="{% static 'image/images2.jpg' %}" alt ="Background image with Laboraroty theme" height = 500px width = 800px>
don't set both height and width, this can lead to image stretching and looking odd. Set one or the other

2022-03-12 00:48 UTC, sselin-co requested changes
Looks good to me! The styling should be applied to the customer and employee home page as well, since the styling currently is only applied to the anonymous homepage.

2022-03-12 00:55 UTC, shepkeira commented
> Looks good to me! The styling should be applied to the customer and employee home page as well, since the styling currently is only applied to the anonymous homepage.

@sselin-co we have separate tickets for the other home pages, so I think that can wait till those tickets (#259 and #260 )

2022-03-12 00:56 UTC, sselin-co commented
> > Looks good to me! The styling should be applied to the customer and employee home page as well, since the styling currently is only applied to the anonymous homepage.
> 
> @sselin-co we have separate tickets for the other home pages, so I think that can wait till those tickets (#259 and #260 )

Thanks for catching that! None issue then 🙂

2022-03-12 00:56 UTC, sselin-co approved these changes
Approved👍

2022-03-12 00:58 UTC, shepkeira requested changes
Please remove the other version of the image without the name change, so we don't have 2 of the same image with different names

2022-03-12 01:01 UTC, shepkeira requested changes

2022-03-12 01:01 UTC, shepkeira commented on LIMS_IMAGE/web/templates/home.html
> +        <h2>Welcome to the LIMS home page</h2>
Sorry my comment was unclear the line
```<h2>Welcome to the LIMS home page</h2>```
line not the the
```<section id = "main">```
line

2022-03-12 01:49 UTC, sayo96825 commented
I tried to remove the old image file and removed the <h2>.
Can you please check again?
Thank you so much 🙏

2022-03-12 04:59 UTC, shepkeira approved these changes

2022-03-12 05:00 UTC, merged