Update on client homepage
shepkeira/LIMS pull request #316
Opened 2022-03-19 00:14 UTC by sayo96825

update on client homepage with background image

2022-03-19 00:30 UTC, shepkeira requested changes
There are two images being added (they are the same image), please only add the one being used

2022-03-19 00:30 UTC, shepkeira commented on LIMS_IMAGE/web/templates/home.html
> +              <img src ="{% static 'image/client-homepage_image.jpg' %}" alt ="Background image with Laboraroty theme" height = 350px>
why did this image change?

2022-03-19 00:30 UTC, shepkeira commented on LIMS_IMAGE/web/templates/orders/home_page.html
> +
Please remove these extra space

2022-03-19 00:34 UTC, shepkeira commented
The image looks really blurry, if you are able to find a large size image/better resolution, that would be good.
If you don't have time, no worries

2022-03-19 01:28 UTC, sayo96825 commented
This image is less blurry.  Please let me know if there is anything else I need to change. 🙏

2022-03-19 04:07 UTC, shepkeira commented
@sayo96825 there are some merge conflicts you will need to fix

2022-03-19 04:13 UTC, shepkeira requested changes
This image is much better, thank you

2022-03-19 04:13 UTC, shepkeira commented on LIMS_IMAGE/web/templates/orders/home_page.html
> +          <img src ="{% static 'image/client_page_image.jpg' %}" alt ="Background image with Laboraroty theme" height = 400px>
this isn't the url of the image you kep

2022-03-19 04:13 UTC, shepkeira commented on LIMS_IMAGE/web/templates/orders/home_page.html
> +    <a href="{% url 'accounts:registration' %}">Sign Up</a>
while you are at it, please remove the indeed extra space at the end of this line

2022-03-19 04:13 UTC, shepkeira commented on LIMS_IMAGE/web/templates/orders/home_page.html
> +          <img src ="{% static 'image/client_page_image.jpg' %}" alt ="Background image with Laboraroty theme" height = 400px>
'image/client-homepage.jpg'

2022-03-22 21:35 UTC, shepkeira commented
@sayo96825 , I fixed your merge changes. Please take a look at them before you merge this PR

2022-03-22 21:35 UTC, shepkeira approved these changes

2022-03-22 22:38 UTC, sayo96825 commented
> @sayo96825 , I fixed your merge changes. Please take a look at them before you merge this PR

Thank you.

2022-03-22 22:39 UTC, merged